DELIMITER $$

DROP PROCEDURE IF EXISTS verify_file_sha512$$

CREATE PROCEDURE verify_file_sha512(fid CHAR(128), hash CHAR(128))
BEGIN
  IF (SELECT 1 FROM users WHERE WWFILEID=fid AND sha512=hash) = 1 THEN 
  SELECT '1';
  ELSE
  SELECT '0';
  END IF;
  
END$$

DELIMITER ;
