DELIMITER $$

DROP PROCEDURE IF EXISTS verify_file_sha1$$

CREATE PROCEDURE verify_file_sha1(hash CHAR(160))
BEGIN
  IF (SELECT 1 FROM files WHERE sha1=hash) = 1 THEN 
  SELECT WWFILEID FROM files WHERE sha1=hash;
  ELSE
  SELECT '-1' AS 'WWFILEID';
  END IF;
  
END$$

DELIMITER ;
